apiVersion: v1
kind: Namespace
metadata:
  name: finance-beni
  labels: 
    name: finance-beni
---
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-beni
spec:
  containers:
  - name: temp-bus
    image: redis:alpine
